#import "@preview/codly:1.3.0": *
#import "@preview/codly-languages:0.1.10": *
  #show: codly-init.with()
#import "@preview/tablem:0.3.0": tablem, three-line-table


#codly(number-format: none)
==  #text(red)[10027] #h(0.25cm) #text(blue)[Language Cardinality] #text(size: 12pt)[(BFS, memorization)]

#table(
  columns: (1fr, 1fr),       
  column-gutter: 0em,        
  stroke: none,              
  align: top + left,         
  [
    A (formal) language is a set of strings. One way to define a particular language is using ordinary set notation. Alternatively, some form of grammar may be more convenient for representing large sets.
    
    The UW grammar in which we are interested has two parts:
      - An initial string
      - A set of replacement rules of the form $s_1 arrow.r s_2$ where $s_1$ and $s_2$ are strings

    The language defined by this grammar is the set of all strings that can be generated by repeatedly replacing $s_1$ by $s_2$ within the initial string. For example, consider the grammar $G$ consisting of the initial string

    ```
    "AyB"
    ```

    and the replacement rules

    ```
    {"A"->"ab", "Ay"->"cdy", "B"->"w", "B"->"x"}. 
    ```

    $G$ generates the language

    ```
    L = {"AyB", "Ayw", "Ayx", "abyB", "abyw", "abyx", "cdyB", "cdyw", "cdyx"}
    ```

    Given a UW grammar $G$, compute how many different strings there are in the language generated by $G$.
  ],
  table.vline(x: 1, stroke: gray),
  [
    一個（形式）語言是一組字串的集合。定義特定語言的一種方法是使用普通的方法——集合表示法。另一種方式是，使用某種形式的文法 (Grammar) 來表示大型集合可能會更方便。#v(1.2em)

    我們感興趣的「UW 文法」包含兩個部分：
      - 一個初始字串
      - 一组格式為 $s_1 arrow.r s_2$ 的替換規則，其中 $s_1$ and $s_2$ 皆為字串#v(1.2em)

    由該文法所定義的語言，是指在初始字串中，透過重複將 $s_1$ 替換為 $s_2$ 所能產生的所有字串之集合。舉例來說，假設有一個文法 $G$，其包含初始字串：#v(2.3em) 

    ```
    "AyB"
    ```

    以及替換規則：

    ```
    {"A"->"ab", "Ay"->"cdy", "B"->"w", "B"->"x"}. 
    ```

    則 $G$ 產生的語言為：

    ```
    L = {"AyB", "Ayw", "Ayx", "abyB", "abyw", "abyx", "cdyB", "cdyw", "cdyx"}
    ```

    給定一個 UW 文法 $G$，請計算該文法 $G$ 所產生的語言中，總共包含多少個不同的字串。
  ]
)



=== #text(red)[Input]
#table(
  columns: (1fr, 1fr),       
  column-gutter: 0em,        
  stroke: none,              
  align: top + left,         
  [
    *The input begins with a single positive integer on a line by itself indicating the number of the cases following, each of them as described below. This line is followed by a blank line, and there is also a blank line between two consecutive inputs.*

    The first line of input contains the initial string. The second and subsequent lines contain the replacement rules, one per line, terminated by end-of-file.

    There are at most 100 replacement rules. Each input string contains between 0 and 10 upper and lower case letters, and is enclosed in quotes. There are no spaces in the input.
  ],
  table.vline(x: 1, stroke: gray),
  [
    *輸入的第一行包含一個單獨的正整數，代表接下來的測資筆數。此行之後會騰出一個空白行，且兩筆連續的輸入之間也會有一個空白行。*#v(2.4em)

    每筆測資的第一行包含初始字串。第二行及後續各行則包含替換規則，每行一條，直到檔案結束（end-of-file）。#v(1.2em)

    替換規則最多不超過 100 條。每個輸入字串包含 0 到 10 個大小寫英文字母，並用雙引號括起來。輸入中不包含任何空格。
  ]
)



=== #text(red)[Output]
#table(
  columns: (1fr, 1fr),       
  column-gutter: 0em,        
  stroke: none,              
  align: top + left,         
  [
    *For each test case, the output must follow the description below. The outputs of two consecutive cases will be separated by a blank line.*

    Output consists of a single integer, the number of distinct strings in the language generated by $G$. If there are more than 1000 distinct strings, print `Too many.` instead.
  ],
  table.vline(x: 1, stroke: gray),
  [
    *對於每筆測資，輸出必須符合以下的說明。兩筆連續測資的輸出之間必須以一個空白行分隔。*#v(1.2em)

    輸出包含一個整數，代表文法 $G$ 所產生的語言中相異字串的數量。如果相異字串的數量超過 1000 個，則改為列印 `Too many.`。
  ]
)



#table(
  columns: (1fr, 1fr),       
  column-gutter: 0em,        
  stroke: none,              
  align: top + left,         
  [
    === #text(red)[Sample Input]
    ```
    1

    "AyB"
    "A"->"ab"
    "Ay"->"cdy"
    "B"->"w"
    "B"->"x"
    ```

  ],
  table.vline(x: 1, stroke: gray),
  [
    === #text(red)[Sample Output]
    ```
    9
    ```
  ]
)



#line(length: 100%, stroke: 1pt + gray)
#codly(number-format: n => text(gray.darken(20%))[#n],)


